import Navbar from "@/components/Navbar";
import Image from "next/image";
import React from "react";
import "./globals.css";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SKEDOSH",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="">
        <header className="fixed top-0 backdrop-blur-md left-0 right-0 z-50  py-5 flex items-center justify-between p-5  bg-white/10 
               border border-white/20 
               transition-all duration-300">
          <Link href={"/"} className="flex items-center">
            <Image
              src="/logo.png"
              alt="Picture of the author"
              width={35}
              height={35}
              className="rounded-xl"
            />
            <h1 className="text-3xl ">SKEDOSH</h1>
          </Link>

          <div className="flex space-x-4 mr-20 text-white font-semibold">
            <Link
              href="/"
              className="px-4 py-2 rounded-xl bg-white/10 
               border border-white/20 hover:bg-white/20
               transition-all duration-300"
            >
              Home
            </Link>

            <Link
              href="/allguns"
              className="px-4 py-2 rounded-xl bg-white/10 backdrop-blur-md
               border border-white/20 hover:bg-white/20
               transition-all duration-300"
            >
              Guns
            </Link>

            <Link
              href="/howitworks"
              className="px-4 py-2 rounded-xl bg-white/10 backdrop-blur-md
               border border-white/20 hover:bg-white/20
               transition-all duration-300"
            >
              How It Works
            </Link>
          </div>

          <div>
            <Link href={"/login"}>
              {" "}
              <button className="btn bg-linear-to-r from-red-200 to-pink-600">
                Login
              </button>{" "}
            </Link>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
