import Image from "next/image";
import React from "react";
import "./globals.css";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import ResponsiveNavbar from "@/components/ResponsiveNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SKEDOSH",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <NextAuthProvider>
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="">
        <ResponsiveNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
    </NextAuthProvider>
  );
};

export default RootLayout;
